apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/apps/middlewares/rabbitmq

patches:
  - path: helmpatch.yaml
    target:
      kind: HelmChartInflationGenerator
      name: rabbitmq
