apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - environments/dev/namespace.yaml
transformers:
  - environments/dev/namespacetransformer.yaml
generators:
  - environments/dev/overlays/rabbitmq
